import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useState, useEffect } from 'react'

export default function Home() {
  const [barang, setBarang] = useState([]);
  const get_barang = async () => {
    const res = await axios.get('http://localhost:3000/api/barang')
    console.log(res.data.data)
    setBarang(res.data.data)
  }
  useEffect(() => {
    get_barang()
  
    
  }, []);
  
  return (
    <div className={styles.container} >
      <Head>
        <title>Inventaris app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Inventaris App</h1>

      {/* <table className={styles.table}>
        <thead className={styles.thead}>
          <tr >
            <th>No</th>
            <th>Nama Barang</th>
            <th>Jumlah</th>

          </tr>
        </thead>
        <tbody className={styles.tableBorder}>
          <tr >
            <td >1</td>
            <td >Komputer</td>
            <td >10</td>
          </tr>


        </tbody>
      </table> */}
      <table className={styles.table}>
        <thead className={styles.thead}>
          <tr >
            <th>No</th>
            <th>Nama Barang</th>
            <th>Jumlah</th>

          </tr>
        </thead>
        <tbody className={styles.tableBorder}>
          {
            barang.map((item, index) => {
              return (
                <tr key={index}>
                  <td>{index + 1}</td>
                  <td>{item.name}</td>
                  <td>{item.qty}</td>
                </tr>
              )
            })
          }

          {/* <tr >
            <td >1</td>
            <td >Komputer</td>
            <td >10</td>
          </tr> */}


        </tbody>
      </table>
      
    </div>
  )
}
