import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import { useState, useEffect } from 'react';

export default function Home() {
  const [barang, setBarang] = useState([]);
  const [dataInputBarang, setDataInputBarang] = useState({});
  const [showForm, setShowForm] = useState({ input: false, edit: false });
  const get_barang = async () => {
    const res = await axios.get('http://localhost:3000/api/barang');
    console.log(res.data.data);
    setBarang(res.data.data);
  };
  useEffect(() => {
    get_barang();
  }, []);
  useEffect(() => {
    // console.log(dataInputBarang);
  }, [dataInputBarang]);

  const submitBarang = async () => {
    try {
      const res = await axios.post('http://localhost:3000/api/barang', {
        name: dataInputBarang.name,
        qty: dataInputBarang.qty,
      });
    } catch (error) {
      console.log(error);
    }
    setDataInputBarang({ name: '', qty: '' }); //reset input
    await get_barang();
  };
  const deleteBarang = async (id) => {
    try {
      const res = await axios.delete(`http://localhost:3000/api/barang`, {
        data: {
          id: id,
        },
      });
      console.log(res);
      console.log(id);
    } catch (error) {
      console.log(error);
    }
    await get_barang();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Inventaris app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Inventaris App</h1>
      {!showForm.input && (
        <button
          onClick={() => setShowForm({ input: true, edit: false })}
          className={styles.inputButton}
        >
          Tambah Barang
        </button>
      )}

      {/* <table className={styles.table}>
        <thead className={styles.thead}>
          <tr >
            <th>No</th>
            <th>Nama Barang</th>
            <th>Jumlah</th>

          </tr>
        </thead>
        <tbody className={styles.tableBorder}>
          <tr >
            <td >1</td>
            <td >Komputer</td>
            <td >10</td>
          </tr>


        </tbody>
      </table> */}

      {showForm.input ? (
        <div className={styles.inputSection}>
          <h3>Input barang</h3>
          <div className={styles.inputForm}>
            <div className={styles.inputField}>
              <label htmlFor='nama'>Nama barang</label>
              <input
                className={styles.inputLabel}
                id='nama'
                type='text'
                value={dataInputBarang.name}
                onChange={(e) => {
                  setDataInputBarang({
                    name: e.target.value,
                    qty: dataInputBarang.qty,
                  });
                }}
              />
            </div>
            <div className={styles.inputField}>
              <label htmlFor='qty'>Jumlah barang</label>
              <input
                className={styles.inputLabel}
                id='qty'
                type='text'
                value={dataInputBarang.qty}
                onChange={(e) =>
                  setDataInputBarang({
                    name: dataInputBarang.name,
                    qty: e.target.value,
                  })
                }
              />
            </div>
            <button
              onClick={() => submitBarang()}
              className={styles.inputButton}
            >
              Simpan
            </button>
          </div>
        </div>
      ) : null}

      <table className={styles.table}>
        <thead className={styles.thead}>
          <tr>
            <th>No</th>
            <th>Nama Barang</th>
            <th>Jumlah</th>
            <th>Hapus</th>
          </tr>
        </thead>
        <tbody className={styles.tableBorder}>
          {barang.map((item, index) => {
            return (
              <tr key={index}>
                <td>{index + 1}</td>
                <td>{item.name}</td>
                <td>{item.qty}</td>
                <td>
                  <button
                    onClick={() => deleteBarang(item.id)}
                    className={styles.inputButton}
                  >
                    Hapus {item.id}
                  </button>
                </td>
              </tr>
            );
          })}

          {/* <tr >
            <td >1</td>
            <td >Komputer</td>
            <td >10</td>
          </tr> */}
        </tbody>
      </table>
    </div>
  );
}
